apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frameforge.fullname" . }}-secrets
  labels:
    {{- include "frameforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  PG_PASSWORD: {{ required "secrets.pgPassword is required" .Values.secrets.pgPassword | quote }}
  MINIO_ACCESS_KEY: {{ required "secrets.minioAccessKey is required" .Values.secrets.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ required "secrets.minioSecretKey is required" .Values.secrets.minioSecretKey | quote }}
  RABBITMQ_PASSWORD: {{ required "secrets.rabbitmqPassword is required" .Values.secrets.rabbitmqPassword | quote }}
  RABBITMQ_URL: {{ printf "amqp://%s:%s@%s:%s" .Values.env.rabbitmqUser .Values.secrets.rabbitmqPassword .Values.env.rabbitmqHost .Values.env.rabbitmqPort | quote }}