apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frameforge.fullname" . }}-worker
  labels:
    {{- include "frameforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      {{- include "frameforge.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "frameforge.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: worker
          image: "{{ .Values.image.worker.repository }}:{{ .Values.image.worker.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.worker.pullPolicy }}
          ports:
            - containerPort: 9090
              name: metrics
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "frameforge.fullname" . }}-config
            - secretRef:
                name: {{ include "frameforge.fullname" . }}-secrets
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          resources:
            {{- toYaml .Values.resources.worker | nindent 12 }}
      restartPolicy: Always